name: App Testing

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ master, iOS ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd iOS
        xcodebuild clean build
    - name: Run tests
      run: xcodebuild clean test
