name: CI/CD

on:
  push:
    branches:
      - feature/functions-ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm install
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}