
name: Firebase Cloud Function Deploy

on:
  push:
    branches: [ master, feature/deployment-fix, feature/deploy-with-service-account ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./API/functions

    strategy:
      matrix:
        node-version: [14.18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        firebaseServiceAccount: "${{ secrets.SERVICE_ACCOUNT }}"
    - name: install libraries
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: install firebase
      run: npm i firebase-tools -g  
    - name: deploy
      working-directory: ./API
      run: firebase deploy --only functions:users_api --token ${{ secrets.FIREBASE_TOKEN }} --project sociable-messenger