name: Firebase Cloud Function Test

on:
  pull_request:
    branches: [ master, sandbox ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./API/functions

    strategy:
      matrix:
        python-version: ['3.8']


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Firebase tools
       run: |
        npm i firebase-tools -g  
    - name: Get Firebase Config
       run: |
        firebase functions:config:get > .runtimeconfig.json 
    - name: Run tests
      run: |
        pytest