name: App Testing

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ master, iOS ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Force XCode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Testing iOS app
      run: exec ./.github/scripts/test_app.sh
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
